export const Tasks = [
    "Interessante Einleitung",
    "Baue rhetorische Fragen ein",
    "Korrekte Aussprache",
    "Nutze Beispiele",
    "Nutze Veranschaulichungen",
    "Modulation",
    "Begeisterung",
    "Argumente der Gegenseite in Betracht ziehen",
    "Hauptgedanken herausstellen",
    "Leicht verständlich formulieren",
    "Positive Argumentation",
    "Motivierend",
    "Wirkungsvoller Schluss",
    "Gestik und Mimik",
    "vermeide Füllwörter",
    "korrekte Haltung",
    "strukturierte Sprechweise",
    "sprich in einem Akzent",
    "imitiere eine bekannte Persönlichkeit",
    "nutze Fremdwörter",
    "bleibe extrem ruhig",
    "sei energisch",
];